# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-11 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.IntegerField(blank=True),
        ),
    ]
